### ISSUE TITLE
One Python file error

### ISSUE THREAD

**Issue by TheSCMGuru** [ochronasec/ochrona-cli#18]
On Windows 10 and in Powershell I ran `ochrona --api_key hidden_key --dir directory_with_one_python_file` and received the following error.
```
,---.     |
|   |,---.|---.,---.,---.,---.,---.
|   ||    |   ||    |   ||   |,---|
`---'`---'`   '`    `---'`   '`---^
                            v. 0.0.17
                            https://ochrona.dev

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\ochrona.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\ochrona\cli.py", line 112, in run
    files = rfind_all_dependencies_files(
  File "c:\python39\lib\site-packages\ochrona\file_handler.py", line 107, in rfind_all_dependencies_files
    raise OchronaFileException("No dependencies files found")
ochrona.exceptions.OchronaFileException: No dependencies files found
```

**Comment by ochronasec** [comment]
Hey @TheSCMGuru thanks for logging the issue. I'll start looking into it asap.

To help troubleshoot could you include what the python file was named?

Also are you able to get any additional context if you run with the `--debug` flag?

**Comment by TheSCMGuru** [comment]
> To help troubleshoot could you include what the python file was named?

wii_remote_1

> Also are you able to get any additional context if you run with the --debug flag?

No additional context.

**Comment by TheSCMGuru** [comment]
The demo worked great, so the program is otherwise working as expected.
