### ISSUE TITLE
Unexpected Response from https://api.ochrona.dev/python/analyze - Internal server error

### ISSUE THREAD

**Issue by deploymentking** [ochronasec/ochrona-cli#19]
Running the latest version of Ochrona v0.0.17 via `pipenv run ochrona` I get the following message:

```
[DEBUG] Unexpected Response from https://api.ochrona.dev/python/analyze - {"message": "Internal server error"}
[!] Unexpected result from analysis, please try again later. If this persists, please report this at https://github.com/ochronasec/ochrona-cli/issues
make: *** [check] Error 1
```

MacOS Big Sur: 11.2.1
Python Version: 3.8.7

Pipfile
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
bandit = "*"
black = "20.8b1"
mypy = "*"
ochrona = "*"

[packages]
flask = "1.1.2"

[requires]
python_version = "3.8.6"
```

ochrona.yml
```
---
debug: true
silent: false
dir: .
report_type: JSON
report_location: ./output
include_dev: true
project_name: pythonsecuritytools
```

Full debug output
```
[DEBUG] Found matching requirements*.txt file at .venv/lib/python3.8/site-packages/pbr/tests/testpackage/test-requirements.txt
[DEBUG] Found matching pipfile.lock file at Pipfile.lock
[DEBUG] Found matching setup.py file at .venv/lib/python3.8/site-packages/mypyc/lib-rt/setup.py
[DEBUG] Found matching setup.py file at .venv/lib/python3.8/site-packages/pbr/tests/test_setup.py
[DEBUG] Found matching setup.py file at .venv/lib/python3.8/site-packages/pbr/tests/testpackage/setup.py
[DEBUG] Found matching setup.py file at .venv/lib/python3.8/site-packages/stevedore/example2/setup.py
[DEBUG] Found matching setup.py file at .venv/lib/python3.8/site-packages/stevedore/example/setup.py
[DEBUG] Discovered dependencies: ["ordereddictpython_version=='2.6'", 'requests-mock']
[DEBUG] Discovered dependencies: ['click==7.1.2', 'flask==1.1.2', 'itsdangerous==1.1.0', 'jinja2==2.11.3', 'markupsafe==1.1.1', 'werkzeug==1.0.1', 'appdirs==1.4.4', 'bandit==1.7.0', 'black==20.8b1', 'certifi==2020.12.5', 'chardet==4.0.0', 'click==7.1.2', 'gitdb==4.0.5', 'gitpython==3.1.13', 'idna==2.10', 'mypy==0.812', 'mypy-extensions==0.4.3', 'ochrona==0.0.17', 'pathspec==0.8.1', 'pbr==5.5.1', 'pyyaml==5.4.1', 'regex==2020.11.13', 'requests==2.25.1', 'six==1.15.0', 'smmap==3.0.5', 'stevedore==3.3.0', 'toml==0.10.2', 'typed-ast==1.4.2', 'typing-extensions==3.7.4.3', 'urllib3==1.26.3']
[DEBUG] Discovered dependencies: []
[DEBUG] Discovered dependencies: ['', 'from', '', 'import', '', 'try:', '', '', 'except', '', '', '', 'import', '', 'from', 'from', 'from', 'from', '', '', 'class', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '_changelog_content', '04316fe\\x00Make', '378261a\\x00Add', '3c373ac\\x00Merge', '182feb3\\x00Fix', 'fa4f46e\\x00Remove', 'd1c53dd\\x00Use', 'a793ea1\\x00Merge', '6c27ce7\\x00Skip', '451e513\\x00Bug', '4c8cfe4\\x00Improve', 'd7e6167\\x00Bug', 'c47ec15\\x00Consider', '8696fbd\\x00Improve', 'f0440f8\\x00Improve', '04984a5\\x00Refactor', 'a65e8ee\\x00Remove', '"""', '', '', 'def', '', '', '', '', '', '', '', '', '', '_old_git_changelog_content', '', '', '', '', 'class', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'class', '', '', '', 'class', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'class', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'class', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
[DEBUG] Unexpected Response from https://api.ochrona.dev/python/analyze - {"message": "Internal server error"}
```

**Comment by ochronasec** [comment]
Thanks for filing @deploymentking 

It looks like the issue here is that ochrona is picking up setup.py files from your virtualenv directories.

I _think_ a workaround would be to call ochrona using the `file` param rather than the `dir` param. (e.g. `file:  ./pipfile.lock`).

However, this does seem like ugly behavior. I'll make a change in the next release to exclude any dependency files found in a virtual environment.

**Comment by deploymentking** [comment]
I tried again using the file pattern using both `./requirements.txt` and `./Pipfile.lock`  I got the following

```
Traceback (most recent call last):
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/bin/ochrona", line 8, in <module>
    sys.exit(run())
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/ochrona/cli.py", line 112, in run
    files = rfind_all_dependencies_files(
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/ochrona/file_handler.py", line 56, in rfind_all_dependencies_files
    files.append(file_obj.name)
AttributeError: 'str' object has no attribute 'name'
make: *** [check] Error 1
```

I thought this might be an issue with using Pipenv so thought I'd give up with Pipenv and pivot to using Poetry and point at the `requirements.txt` output via `poetry export -o requirements.txt` and got the following 

```
Traceback (most recent call last):
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/bin/ochrona", line 8, in <module>
    sys.exit(run())
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/ochrona/cli.py", line 112, in run
    files = rfind_all_dependencies_files(
  File "/Users/leemyring/source/deploymentking/pythonsecuritytools/.venv/lib/python3.8/site-packages/ochrona/file_handler.py", line 56, in rfind_all_dependencies_files
    files.append(file_obj.name)
AttributeError: 'str' object has no attribute 'name'
make: *** [check] Error 1
```

pyproject.toml
```
[tool.poetry]
name = "pythonsecuritytools"
version = "0.1.0"
description = "Test linting and security tools for CI/CD"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
bandit = "^1.7.0"
black = "^20.8b1"
mypy = "^0.812"
ochrona = "^0.0.17"
Flask = "^1.1.2"
urllib3 = "^1.26.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by ochronasec** [comment]
Hi @deploymentking, thanks for testing. This should be enough for me to run with. I've marked the issue as a bug and will try to resolve as soon as possible.

**Comment by deploymentking** [comment]
🎉 awesome 😄 
https://github.com/deploymentking/pythonsecuritytools is source repo just in case you need it

**Comment by ochronasec** [comment]
@deploymentking I believe the `AttributeError` you were seeing should be fixed in v0.0.18.

However, the fix right now does not address excluding dependency files in your virtualenv, I'm still thinking through whether there could be a possible use case for those, or if there's a better way to handle them.

**Comment by deploymentking** [comment]
Can confirm that `v0.0.18` has fixed the issue. 🎉.... but only when specifying a `file: requirements.txt`

When I select `dir:` I still got issues with scanning the `.venv` folder even when I specify it as an exclude_dir. 😞 As a general rule I always have a local `.venv` folder in all my projects and the `dir: .` option still has issues (as you mentioned it would)

Then I tried a few different combinations with varying degrees of success. I thought it might help to post the results here.
One key thing I noted was that I had `include_dev` set to `true` but had no dev dependencies and I think that might have been causing issues.

Test 1 (just poetry.lock present in folder structure)
```
---
debug: true
silent: false
dir: .
exclude_dir: .venv
include_dev: true
project_name: pythonsecuritytools
``` 

```
[DEBUG] Found matching poetry.lock file at poetry.lock
[DEBUG] Discovered dependencies: ['appdirs==1.4.4', 'bandit==1.7.0', 'black==20.8b1', 'certifi==2020.12.5', 'chardet==4.0.0', 'click==7.1.2', 'colorama==0.4.4', 'flask==1.1.2', 'gitdb==4.0.5', 'gitpython==3.1.13', 'idna==2.10', 'itsdangerous==1.1.0', 'jinja2==2.11.3', 'markupsafe==1.1.1', 'mypy==0.812', 'mypy-extensions==0.4.3', 'ochrona==0.0.18', 'pathspec==0.8.1', 'pbr==5.5.1', 'pyyaml==5.4.1', 'regex==2020.11.13', 'requests==2.25.1', 'six==1.15.0', 'smmap==3.0.5', 'stevedore==3.3.0', 'toml==0.10.2', 'typed-ast==1.4.2', 'typing-extensions==3.7.4.3', 'urllib3==1.26.3', 'werkzeug==1.0.1']
Report 1 of 1
╞=============================================================================================================================================================================╡
| Source: poetry.lock
╞=============================================================================================================================================================================╡
| ✅  No Vulnerabilities detected
╞=============================================================================================================================================================================╡
```

Test 2 (both poetry.lock *and* requirements.txt present in folder structure. I sometimes export a requirements.txt file to use a Docker build that does not have poetry installed)
```
---
debug: true
silent: false
dir: .
exclude_dir: .venv
include_dev: true
project_name: pythonsecuritytools
``` 

```
[DEBUG] Found matching requirements*.txt file at requirements.txt
[DEBUG] Found matching poetry.lock file at poetry.lock
[DEBUG] Discovered dependencies: ['appdirs==1.4.4', 'bandit==1.7.0', 'black==20.8b1', 'click==7.1.2', 'colorama==0.4.4', 'flask==1.1.2', 'gitdb==4.0.5', 'gitpython==3.1.13', 'itsdangerous==1.1.0', 'jinja2==2.11.3', 'markupsafe==1.1.1', 'mypy-extensions==0.4.3', 'mypy==0.812', 'pathspec==0.8.1', 'pbr==5.5.1', 'pyyaml==5.4.1', 'regex==2020.11.13', 'six==1.15.0', 'smmap==3.0.5', 'stevedore==3.3.0', 'toml==0.10.2', 'typed-ast==1.4.2', 'typing-extensions==3.7.4.3', 'urllib3==1.26.3', 'werkzeug==1.0.1']
[DEBUG] Discovered dependencies: ['appdirs==1.4.4', 'bandit==1.7.0', 'black==20.8b1', 'certifi==2020.12.5', 'chardet==4.0.0', 'click==7.1.2', 'colorama==0.4.4', 'flask==1.1.2', 'gitdb==4.0.5', 'gitpython==3.1.13', 'idna==2.10', 'itsdangerous==1.1.0', 'jinja2==2.11.3', 'markupsafe==1.1.1', 'mypy==0.812', 'mypy-extensions==0.4.3', 'ochrona==0.0.18', 'pathspec==0.8.1', 'pbr==5.5.1', 'pyyaml==5.4.1', 'regex==2020.11.13', 'requests==2.25.1', 'six==1.15.0', 'smmap==3.0.5', 'stevedore==3.3.0', 'toml==0.10.2', 'typed-ast==1.4.2', 'typing-extensions==3.7.4.3', 'urllib3==1.26.3', 'werkzeug==1.0.1']
[DEBUG] Unexpected Response from https://api.ochrona.dev/python/analyze - {"message": "Internal server error"}
[!] Unexpected result from analysis, please try again later. If this persists, please report this at https://github.com/ochronasec/ochrona-cli/issues
make: *** [check] Error 1
```

Test 3 (both poetry.lock *and* requirements.txt present in folder structure)
```
---
debug: true
silent: false
file: requirements.txt
include_dev: true
project_name: pythonsecuritytools
```

```
<class 'str'> requirements.txt
[DEBUG] Discovered dependencies: ['appdirs==1.4.4', 'bandit==1.7.0', 'black==20.8b1', 'click==7.1.2', 'colorama==0.4.4', 'flask==1.1.2', 'gitdb==4.0.5', 'gitpython==3.1.13', 'itsdangerous==1.1.0', 'jinja2==2.11.3', 'markupsafe==1.1.1', 'mypy-extensions==0.4.3', 'mypy==0.812', 'pathspec==0.8.1', 'pbr==5.5.1', 'pyyaml==5.4.1', 'regex==2020.11.13', 'six==1.15.0', 'smmap==3.0.5', 'stevedore==3.3.0', 'toml==0.10.2', 'typed-ast==1.4.2', 'typing-extensions==3.7.4.3', 'urllib3==1.26.3', 'werkzeug==1.0.1']
Report 1 of 1
╞=============================================================================================================================================================================╡
| Source: requirements.txt
╞=============================================================================================================================================================================╡
| ✅  No Vulnerabilities detected
╞=============================================================================================================================================================================╡
```

Test 4 (both poetry.lock *and* requirements.txt present in folder structure. No dev dependencies)
```
---
debug: true
silent: false
file: requirements.txt
include_dev: true
project_name: pythonsecuritytools
```

```
<class 'str'> requirements.txt
[DEBUG] Discovered dependencies: ['appdirs==1.4.4', 'bandit==1.7.0', 'black==20.8b1', 'click==7.1.2', 'colorama==0.4.4', 'flask==1.1.2', 'gitdb==4.0.5', 'gitpython==3.1.13', 'itsdangerous==1.1.0', 'jinja2==2.11.3', 'markupsafe==1.1.1', 'mypy-extensions==0.4.3', 'mypy==0.812', 'pathspec==0.8.1', 'pbr==5.5.1', 'pyyaml==5.4.1', 'regex==2020.11.13', 'six==1.15.0', 'smmap==3.0.5', 'stevedore==3.3.0', 'toml==0.10.2', 'typed-ast==1.4.2', 'typing-extensions==3.7.4.3', 'urllib3==1.26.3', 'werkzeug==1.0.1']
Report 1 of 1
╞=============================================================================================================================================================================╡
| Source: requirements.txt
╞=============================================================================================================================================================================╡
| ✅  No Vulnerabilities detected
╞=============================================================================================================================================================================╡

```

I did get some "weirdness" around needing to have quotes around the dir value e.g. `dir: ".venv"` in order to prevent it scanning my virtualenv, but then it stopped behaving weirdly and worked with and without quotes as expected, so I don't know if something else changed that I hadn't noted.

**Comment by deploymentking** [comment]
tl;dr
* running with both a requirements file and a poetry lock file whilst specifying dir caused issues
* not excluding a local virtualenv caused issues

as you say, there might be value in scanning a virtualenv?

**Comment by ochronasec** [comment]
Thanks so much for the thorough testing @deploymentking.

Let me take these findings and see if I can find a more reliable solution to the issues that you're seeing.

**Comment by ochronasec** [comment]
Hi @deploymentking, I believe these new errors were on the server side. I've made a change there to address what seems to have been the problem.  

I'm going to close this for now, but let me know if you see anything else that doesn't seem right.
