### ISSUE TITLE
unbalanced parenthesis error

### ISSUE THREAD

**Issue by JadEidSewts** [ochronasec/ochrona-cli#57]
I ran into this error when running Ochrona in a venv: 

`Traceback (most recent call last):
  File "/home/user/project/.venv/bin/ochrona", line 8, in <module>
    sys.exit(run())
  File "/home/user/project/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/project/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/user/project/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/project/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/project/.venv/lib/python3.8/site-packages/ochrona/cli/cli.py", line 144, in run
    results.append(resolve(**payload))
  File "/home/user/project/.venv/lib/python3.8/site-packages/ochrona/eval/eval.py", line 23, in resolve
    vulns += db.lookup_by_name(_safe_query_name(dep))
  File "/home/user/project/.venv/lib/python3.8/site-packages/ochrona/db/db.py", line 95, in lookup_by_name
    if re.match(VULN_PATTERN.format(name), vuln.name):
  File "/usr/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 13
`

**Comment by ochronasec** [comment]
Hi @JadEidSewts can you share any other details about your environment? What kind of dependency file(s) do you have present and what dependencies are included?

**Comment by JadEidSewts** [comment]
I don't know if I'm permitted to share that information. Could you maybe tell me what its trying to parse so I can look into that instead?

**Comment by ochronasec** [comment]
Hey @JadEidSewts, Ochrona will attempt to locate any files that may contain information about the dependencies used by your python project, for example `requirements.txt`, `poetry.lock`, etc. If it locates a file it will attempt to parse information about the packages used and their versions, then check for any known vulnerabilities in those packages. 

Judging from the error it looks like it came when trying to look up a dependency used by your project in the vulnerability database. It must've contained some characters that caused a regex error. I can apply a broad fix here, but it would be useful to know exactly what is causing the error so I can be confident I've fixed the problem completely.

**Comment by JadEidSewts** [comment]
Yes, I thought it probably came across some strange characters but I still can't find the source. In any case, I will restrict it to go through a limited portion of the repo. Thanks for your help :)
